### ISSUE TITLE
Undo/Redo feels strange for changes in panels

### ISSUE THREAD

**Issue by obuchtala** [substance/writer#1]
We need to think about a way to recover the writer state along with the undone operation.
It would be possible to store something into the DocumentChange data as we do with selectionBefore and ~After.

@michael any ideas?

**Comment by michael** [comment]
Yeah there's a missing concept somehow. Ideally you should be able to follow each undone change on screen. As you said we could record the writer state associated with a change for reconstructing the situation before and after that change.

**Comment by obuchtala** [comment]
Could you sketch what would need to be saved so that writer could recover that on undo/redo?

**Comment by michael** [comment]
this.state of the Writer component? and then on undo/redo make writerCtrl.replaceState() with what's stored on the change.

**Comment by obuchtala** [comment]
Do we need to be careful with reflexive transitions? I.e., check if the state is really different? or is react smart enough? Or is it simply ok to just 'rerender'...

**Comment by michael** [comment]
I would say ok to re-render, and often needed. To stop rerendering reflexive transitions we can implement componentShouldUpdate on the Writer comp. Needs a deep equality check on the current state with nextState.

**Comment by obuchtala** [comment]
Ok... then I need to override TransactionDocument.save() (or make it configurable) to store app relevant data. Also the selection is actually that kind of data.
And undo/redo would be handled by writer (state update + selection update).

**Comment by michael** [comment]
Sounds good.

What I forgot to say. There's a soft rule for writer states that they can only consist plain objects.
